export const labels: Record<string, string> = {
  normal: "예측 준비",
  observations_available: "실측 자료 확보",
  synthetic_available: "시뮬레이션 자료 확보",
  experimental: "실험 연결",
  seoul_source_date_join: "서울 원천 날짜 결합",
  unapproved: "매핑 미승인",
  unverified: "확인 필요",
  verified: "확인 완료",
  experimental_gate_passed: "실험 기준 충족 · 운영 미승인",
  catalog_only: "위치 정보만 확보",
  active: "모델 사용 가능",
  experimental_ready: "실험 학습 준비",
  not_ready: "모델 미준비",
  ready: "준비 완료",
  pending: "대기",
  queued: "대기",
  running: "실행 중",
  completed: "완료",
  failed: "실패",
  interrupted: "중단",
  promoted: "교체 완료",
  rejected: "기존 유지",
  warn: "확인 필요",
  warning: "확인 필요",
  open: "미확인",
  acknowledged: "확인 중",
  resolved: "조치 완료",
  recorded: "기록",
  data_required: "자료 필요",
  model_not_ready: "모델 준비 필요",
  data_gap: "연속 자료 부족",
  stale_data: "자료 갱신 필요",
  evaluation_pending: "평가 대기",
  evaluation_passed: "평가 기준 충족",
  synthetic: "합성 자료",
  observed: "실측 자료",
  observed_api: "외부 API 관측",
  unit_verification_required: "수위 기준 대조 필요",
  blocked: "준비 조건 미충족",
  quality_rejected: "품질 기준 미달",
};
